/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_updatePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MembersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MembersController_list"];
        put?: never;
        post: operations["MembersController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["MembersController_remove"];
        options?: never;
        head?: never;
        patch: operations["MembersController_changeRole"];
        trace?: never;
    };
    "/api/action-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ActionPlansController_list"];
        put?: never;
        post: operations["ActionPlansController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/action-plans/{planId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ActionPlansController_get"];
        put: operations["ActionPlansController_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/action-plans/{planId}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ActionPlansController_listActions"];
        put?: never;
        post: operations["ActionPlansController_createAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/{actionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ActionsController_get"];
        put: operations["ActionsController_update"];
        post?: never;
        delete: operations["ActionsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/{actionId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ActionsController_transition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/{actionId}/rejection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ActionsController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** @example Clinique des Lilas */
            organizationName: string;
            /** @example Alice Martin */
            name: string;
            /** @example alice@lilas.fr */
            email: string;
            password: string;
        };
        SessionResponse: {
            /** @description Vrai avec un mot de passe temporaire : seul son changement est permis (D8) */
            mustChangePassword: boolean;
        };
        LoginRequest: {
            /** @example alice@lilas.fr */
            email: string;
            password: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        CurrentMemberResponse: {
            /** Format: uuid */
            userId: string;
            name: string;
            email: string;
            /** @enum {string} */
            role: "MEMBER" | "MANAGER" | "ADMIN";
            /** Format: uuid */
            organizationId: string;
            organizationName: string;
            mustChangePassword: boolean;
        };
        MemberResponse: {
            /** Format: uuid */
            userId: string;
            name: string;
            email: string;
            /** @enum {string} */
            role: "MEMBER" | "MANAGER" | "ADMIN";
        };
        AddMemberRequest: {
            email: string;
            name: string;
            /** @enum {string} */
            role: "MEMBER" | "MANAGER" | "ADMIN";
        };
        AddedMemberResponse: {
            /** Format: uuid */
            userId: string;
            /** @description Affiché une seule fois, à transmettre au membre (D8) */
            temporaryPassword: string;
        };
        ChangeRoleRequest: {
            /** @enum {string} */
            role: "MEMBER" | "MANAGER" | "ADMIN";
        };
        ActionPlanResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string | null;
            /** @description Aussi rendue dans l’en-tête ETag, à renvoyer en If-Match (D14) */
            version: number;
        };
        TitledRequest: {
            title: string;
            description?: string | null;
        };
        ActionResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string | null;
            /** @description Aussi rendue dans l’en-tête ETag, à renvoyer en If-Match (D14) */
            version: number;
            /** Format: uuid */
            planId: string;
            /** @enum {string} */
            status: "TODO" | "IN_PROGRESS" | "TO_VALIDATE" | "DONE";
        };
        AuthorResponse: {
            /** Format: uuid */
            userId: string;
            name: string | null;
        };
        StatusChangeResponse: {
            /** @enum {string} */
            from: "TODO" | "IN_PROGRESS" | "TO_VALIDATE" | "DONE";
            /** @enum {string} */
            to: "TODO" | "IN_PROGRESS" | "TO_VALIDATE" | "DONE";
            /** Format: date-time */
            at: string;
            reason: string | null;
            author: components["schemas"]["AuthorResponse"];
        };
        ActionDetailResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string | null;
            /** @description Aussi rendue dans l’en-tête ETag, à renvoyer en If-Match (D14) */
            version: number;
            /** Format: uuid */
            planId: string;
            /** @enum {string} */
            status: "TODO" | "IN_PROGRESS" | "TO_VALIDATE" | "DONE";
            history: components["schemas"]["StatusChangeResponse"][];
        };
        ChangeStatusRequest: {
            /** @enum {string} */
            to: "TODO" | "IN_PROGRESS" | "TO_VALIDATE" | "DONE";
        };
        RejectionRequest: {
            reason: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    AuthController_signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    AuthController_signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_updatePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentMemberResponse"];
                };
            };
        };
    };
    MembersController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"][];
                };
            };
        };
    };
    MembersController_add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddedMemberResponse"];
                };
            };
        };
    };
    MembersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembersController_changeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoleRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ActionPlansController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionPlanResponse"][];
                };
            };
        };
    };
    ActionPlansController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TitledRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionPlanResponse"];
                };
            };
        };
    };
    ActionPlansController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionPlanResponse"];
                };
            };
        };
    };
    ActionPlansController_update: {
        parameters: {
            query?: never;
            header: {
                /** @description ETag lu, ex. "3" (D14) */
                "If-Match": string;
            };
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TitledRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionPlanResponse"];
                };
            };
        };
    };
    ActionPlansController_listActions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"][];
                };
            };
        };
    };
    ActionPlansController_createAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TitledRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDetailResponse"];
                };
            };
        };
    };
    ActionsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDetailResponse"];
                };
            };
        };
    };
    ActionsController_update: {
        parameters: {
            query?: never;
            header: {
                /** @description ETag lu, ex. "3" (D14) */
                "If-Match": string;
            };
            path: {
                actionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TitledRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDetailResponse"];
                };
            };
        };
    };
    ActionsController_remove: {
        parameters: {
            query?: never;
            header: {
                /** @description ETag lu, ex. "3" (D14) */
                "If-Match": string;
            };
            path: {
                actionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ActionsController_transition: {
        parameters: {
            query?: never;
            header: {
                /** @description ETag lu, ex. "3" (D14) */
                "If-Match": string;
            };
            path: {
                actionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeStatusRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDetailResponse"];
                };
            };
        };
    };
    ActionsController_reject: {
        parameters: {
            query?: never;
            header: {
                /** @description ETag lu, ex. "3" (D14) */
                "If-Match": string;
            };
            path: {
                actionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDetailResponse"];
                };
            };
        };
    };
}
